FROM rocm/dev-ubuntu-24.04:6.4.4-complete

RUN apt update && \
    apt install -y build-essential && \
    apt install -y python3 python3-pip \
    apt clean

pip3 install torch torchvision --index-url https://download.pytorch.org/whl/rocm6.4

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /workdir

WORKDIR /workdir
